### ISSUE TITLE
Merge in other pulls

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/FSLineChart#2]
Like https://github.com/ArthurGuibert/FSLineChart/pull/25

And invite contributors to continue here

**Comment by fulldecent** [comment]
- [ ] Review if https://github.com/ArthurGuibert/FSLineChart/pull/23 is still a problem in this library. Then make a note there.

**Comment by yaroslav-zhurakovskiy** [comment]
As for https://github.com/ArthurGuibert/FSLineChart/pull/23. It seems like everything works fine. I added some tests for it. Check out my pull request https://github.com/fulldecent/FSLineChart/pull/5.

**Comment by fulldecent** [comment]
Thank you. I added a note there.
